### ISSUE TITLE
cargo classpath configuration doesn't work?

### ISSUE THREAD

**Issue by nikomatsakis** [duchess-rs/duchess#7]
I've setup a [.config/cargo.toml](https://github.com/nikomatsakis/duchess/blob/main/.cargo/config.toml) that sets the classpath, but when I run

```bash
cargo run --example logger
```

it doesn't seem to be set. I don't understand why and that's confusing. HELP!

**Comment by fpoli** [comment]
I think it's a cache invalidation issue with procedural macros that depend on environment variables: https://github.com/rust-lang/rust/issues/74690.

I tried actually reading `CLASSPATH` instead of using the hardcoded `java` for `javap`. The result is that modifying the `CLASSPATH` in `.cargo/config` does not trigger a recompilation of the example, but after a `cargo clean` duchess uses the modified classpath.

**Comment by nikomatsakis** [comment]
Ah, @fpoli, that's perhaps right. Is there a "correct way" to fix this?

**Comment by fpoli** [comment]
The correct fix seems to be https://github.com/rust-lang/rust/issues/99515, but in the meantime https://github.com/duchess-rs/duchess/pull/35 should work fine.
